### ISSUE TITLE
PlantEasily --- Cosmetic (I think) bug on 0.217.30

### ISSUE THREAD

**Issue by Lord-Kamina** [AdvizeGH/Advize_ValheimMods#13]
First: I don't think it's actually a new thing in this version, most likely it has to do with the engine update or somesuch and I just noticed.
I _think_ it's just cosmetic, but the grid count label is not working properly. Specifically, it appears it's showing only the first digit for the count in either columns or rows. Here's some pics:

![20231113204943_1](https://github.com/AdvizeGH/Advize_ValheimMods/assets/6446892/823ea339-617a-4268-a37f-d26f46d7b7bc)
![20231113205023_1](https://github.com/AdvizeGH/Advize_ValheimMods/assets/6446892/df2cda4c-270c-4168-8263-6a94161520c2)
![20231113205034_1](https://github.com/AdvizeGH/Advize_ValheimMods/assets/6446892/f09fe707-00d6-45e4-9f89-936ea67f39af)
![20231113205154_1](https://github.com/AdvizeGH/Advize_ValheimMods/assets/6446892/8e5516e0-9741-4217-878f-d9a7cd50adb5)

**Comment by AdvizeGH** [comment]
Thanks for the report. There are some settings in the mod related to this under the [UI] category of settings. In your screenshots you appear to have [UI]CostDisplayStyle set to TotalCount. This won't show rows and columns, it instead will show the required amount per placement x total number of placement ghosts. Something really strange is going on with the text in that UI element and I suspect it may be due to another mod being present. In all 3 screenshots the last digit is missing. In order they should read 54/1x9, 54/1x18, 54/1x10, and 54/1x20. I'll do what I can to figure out what's happening here.

In the meanwhile may I suggest changing CostDisplayStyle to FullCost. Perhaps you'll have ebetter luck with that.

**Comment by Lord-Kamina** [comment]
I'll check it out when I can.

Othee mods I've installed are chiefly planteverything, and can't from containers. (There's a bunch more but I doubt they're contributing to the issue)

**Comment by AdvizeGH** [comment]
I've received no further reports of this and am inclined to believe it's not a mod issue.
