### ISSUE TITLE
Not working in public test server

### ISSUE THREAD

**Issue by Wmonnh6** [AdvizeGH/Advize_ValheimMods#20]
Plant everything is an amazing mod that I am always using and it does not currently work with the ashlands public test server. I assume it will be updated when the ashlands actually releases however I was curious if it was possible to have it work with the public test server? I really want to get my hands on the new build pieces and start building a creative world and I love using this mod as it is very helpful and makes building/farming very easy to do and allows me to perfectly place any kind of vegetation I desire. I know this is a stretch but I wanted to reach out about the possibility of having it updated to work on the public test server on thunderstore as I am an avid fan of this mod. I understand if that is not possible, just wanted to see if it was a possibility thank you.

**Comment by AdvizeGH** [comment]
I've been reluctant to do this due to logistical issues concerning people using PTB and those not, and how to handle versioning to ensure mod managers see an official update when appropriate. Also, it really is against the spirit of the PTB to be using mods and overall I have never supported mod use on the PTB. What I will do, however, is push my current WIP fixes and allow people to build it if they have the know-how to do so.
