### ISSUE TITLE
Spyglass wont zoom

### ISSUE THREAD

**Issue by TheCloudCrafter** [AdvizeGH/Advize_ValheimMods#8]
Just made the spyglass for the first time.
Zoom isn't working for me. 
Worked first time.
Then on second try i block instead of zoom.

Tried new keybind and it still doesnt work.

**Comment by AdvizeGH** [comment]
Sorry, the mod is likely not compatible with the game since the recent game and BepInEx updates. Will need to re-rip the game, remake the asset bundle, and double check the code still functions. No ETA on this unfortunately. I might be separating the spyglass from the skill anyways and making it into its own mod.

**Comment by TheCloudCrafter** [comment]
> Sorry, the mod is likely not compatible with the game since the recent game and BepInEx updates. Will need to re-rip the game, remake the asset bundle, and double check the code still functions. No ETA on this unfortunately. I might be separating the spyglass from the skill anyways and making it into its own mod.

Skill seems to work as intended. I just got to make the spyglass. Whats interesting is if you try enough times in rapid succession it works. Leading me to believe it was a keybinding issue. But when I switched it to an unused key it still doesn't work as intended.
