### ISSUE TITLE
Grid planting gives unexpeted results

### ISSUE THREAD

**Issue by gacekssj4** [AdvizeGH/Advize_ValheimMods#9]
Planting as grid plants where  I stand, isntead where I point cursor to. 

I made movie: https://youtu.be/w4FU3ko9amY

**Comment by AdvizeGH** [comment]
Do you have Farming by smoothbrain installed? That's what this looks like. Press your configured hotkeys for toggling off snapping and mass planting in the Farming mod (I think they are left ctrl and left shift by default).

**Comment by AdvizeGH** [comment]
Watching the video again, I don't know how you've accomplished that, it isn't the normal behavior. It'll have to be a mod conflict of some kind.

**Comment by gacekssj4** [comment]
I had MassFarming mod installed. I thought i removed it. Because I wanted to switch to your mod.|
After removing massfarming.dll it seems to be work fine.

**Comment by AdvizeGH** [comment]
Sweet! Enjoy the mod :smile_cat:

**Comment by seigieu** [comment]
> Sweet! Enjoy the mod smile_cat

Thank you. But I think i will go back to MassFarming and stay with your other mod.

FYI: This autosnap feature is cool. However i find 2 things that I do not like:
First, is if I plant 5x5 then if any seed will be red, its not ommited, instead everything is blocked (MassFarming just ignores plants it can't plant). So I can plant irregular fields with MassFarming, but with your I need to spend lots of time to adjust size so it fits.
Basically 3 things block your mod from planting, and MassFarming just ignores plants it can't plant
- Something is in way
- Ground is not raked/prepared (between raked paths)
- There are not enough seeds

So basically, mass farming is better suited for mass farming, and your seems to be better suited for fine "in-grid" layout. 
I don't need precision, I need to plant plants with as low effort as possible.

Second. Autosnap is picky. It sometimes happens when i have it aligned, and want will more too much right/left, snapping orientation changes. Mass farming on the other hand, allows rotation with scroll. Which (by me) allows more control.

Otherwise, great mod!

**Comment by gacekssj4** [comment]
> Sweet! Enjoy the mod smile_cat

Thank you. But I think i will go back to MassFarming and stay with your other mod.

FYI: This autosnap feature is cool. However i find 2 things that I do not like:
First, is if I plant 5x5 then if any seed will be red, its not ommited, instead everything is blocked (MassFarming just ignores plants it can't plant). So I can plant irregular fields with MassFarming, but with your I need to spend lots of time to adjust size so it fits.
Basically 3 things block your mod from planting, and MassFarming just ignores plants it can't plant

-  Something is in way
- Ground is not raked/prepared (between raked paths)
- There are not enough seeds

So basically, mass farming is better suited for mass farming, and your seems to be better suited for fine "in-grid" layout.
I don't need precision, I need to plant plants with as low effort as possible.

Second. Autosnap is picky. It sometimes happens when i have it aligned, and want will more too much right/left, snapping orientation changes. Mass farming on the other hand, allows rotation with scroll. Which (by me) allows more control.

Otherwise, great mod!
